import type { InsuranceMapPin } from './insurance-portal-map.types';

/** Meridyen Hasar Ağı vitrin pinleri — yalnızca sunum modunda gösterilir */
export const INSURANCE_PORTAL_SHOWCASE_PINS: InsuranceMapPin[] = [
  {
    id: 'vitrin-kibris',
    latitude: 35.1856,
    longitude: 33.3823,
    label: 'Kıbrıs Bölge Desteği',
    tooltip: 'Bölgesel Operasyon Merkezi',
    category: 'generic',
    isShowcase: true,
    city: 'Lefkoşa',
  },
  {
    id: 'vitrin-yat-marmaris',
    latitude: 36.855,
    longitude: 28.274,
    label: 'Yat Hasarı',
    tooltip: 'Deniz Aracı Onarımı',
    category: 'marine',
    isShowcase: true,
    city: 'Muğla',
  },
  {
    id: 'vitrin-yat-bodrum',
    latitude: 37.034,
    longitude: 27.43,
    label: 'Tekne Motor Tamiri',
    tooltip: 'Deniz Aracı Bakım',
    category: 'marine',
    isShowcase: true,
    city: 'Muğla',
  },
  {
    id: 'vitrin-fabrika-kocaeli',
    latitude: 40.77,
    longitude: 29.95,
    label: 'Fabrika Hasarı',
    tooltip: 'Endüstriyel Tesis Onarımı',
    category: 'industrial',
    isShowcase: true,
    city: 'Kocaeli',
  },
  {
    id: 'vitrin-fabrika-izmir',
    latitude: 38.46,
    longitude: 27.18,
    label: 'Sanayi Tesis Hasarı',
    tooltip: 'Fabrika Hasarı',
    category: 'industrial',
    isShowcase: true,
    city: 'İzmir',
  },
  {
    id: 'vitrin-konut-ankara',
    latitude: 39.925,
    longitude: 32.866,
    label: 'Cam Yenileme',
    tooltip: 'Konut Hasarı',
    category: 'residential',
    isShowcase: true,
    city: 'Ankara',
  },
  {
    id: 'vitrin-konut-istanbul',
    latitude: 41.02,
    longitude: 29.01,
    label: 'Klima Tamiri',
    tooltip: 'Konut Teknik Servis',
    category: 'residential',
    isShowcase: true,
    city: 'İstanbul',
  },
  {
    id: 'vitrin-konut-antalya',
    latitude: 36.91,
    longitude: 30.695,
    label: 'Su Baskını Onarımı',
    tooltip: 'Konut Hasarı',
    category: 'residential',
    isShowcase: true,
    city: 'Antalya',
  },
  {
    id: 'vitrin-generic-trabzon',
    latitude: 41.0,
    longitude: 39.72,
    label: 'Motor Tamiri',
    tooltip: 'Genel Hasar Müdahalesi',
    category: 'generic',
    isShowcase: true,
    city: 'Trabzon',
  },
  {
    id: 'vitrin-generic-gaziantep',
    latitude: 37.07,
    longitude: 37.38,
    label: 'Elektrik Arızası',
    tooltip: 'Acil Müdahale',
    category: 'generic',
    isShowcase: true,
    city: 'Gaziantep',
  },
];
