/** Adım içerikleri için lokal önizleme sabitleri — gerçek API sonucu değildir. */

export const PREVIEW = {
  fileNo: 'HD-2026-0042',
  statusLabel: 'Açık',
  insuredName: 'Ahmet Yılmaz',
  insuredPhone: '0532 133 41 44',
  insurer: 'Anadolu Sigorta',
  lossType: 'Su Baskını',
  noticeAt: '18.07.2026 09:15',
  appointmentAt: '19.07.2026 10:30',
  appointmentDate: '19.07.2026',
  appointmentTime: '10:30',
  durationMinutes: '90',
  locationUrl: 'https://maps.example/moda-12',
  address: 'Moda Cad. No:12 D:4 Kadıköy / İstanbul',
  district: 'Kadıköy',
  owner: 'Ayşe Operatör',
  completedCount: 2,
  totalCount: 8,
  completionPct: 25,
  eta: '22.07.2026 16:30',
  insuredApproval: false,
  people: [
    { initials: 'AO', name: 'Ayşe Operatör', role: 'Dosya Sorumlusu', status: 'Atandı' as const },
    { initials: 'MK', name: 'Mehmet Kaya', role: 'Dosya Operatörü', status: 'Atandı' as const },
    { initials: 'T', name: '—', role: 'Tespitçi (Boyacı)', status: 'Atanmadı' as const },
    { initials: 'T', name: '—', role: 'Tedarikçi (Sıhhi Tesisat)', status: 'Atanmadı' as const },
  ],
  notes: [
    {
      who: 'Ayşe Operatör',
      when: '18.07 · 14:10',
      text: 'Sigortalı randevu saatini sabah istedi.',
    },
    {
      who: 'Mehmet Kaya',
      when: '17.07 · 16:40',
      text: 'Önceki dosyada hızlı dönüş sağlandı.',
    },
  ],
  progressLines: [
    { state: 'done' as const, text: 'Sigortalı ile görüşme tamamlandı', when: '18.07.2026 14:10', step: 'insured_appointment' as const },
    { state: 'done' as const, text: 'Randevu oluşturuldu', when: '19.07.2026 10:30', step: 'insured_appointment' as const },
    { state: 'done' as const, text: 'Tespitçi ataması yapıldı', when: '19.07.2026 11:05', step: 'inspector' as const },
    { state: 'waiting' as const, text: 'Tedarikçi ataması bekleniyor', when: null, step: 'supplier' as const },
    { state: 'future' as const, text: 'WhatsApp bilgilendirme bekleniyor', when: null, step: 'whatsapp' as const },
    { state: 'future' as const, text: 'Dijital onay bekleniyor', when: null, step: 'digital_approval' as const },
    { state: 'future' as const, text: 'Rapor yazım aşamasında', when: null, step: 'report_writing' as const },
    { state: 'future' as const, text: 'Onaya gönderilecek', when: null, step: 'sent_for_approval' as const },
    { state: 'future' as const, text: 'Onay bekleniyor', when: null, step: 'approved' as const },
  ],
  risks: [
    { tone: 'critical' as const, text: 'Tedarikçi ataması 2 saattir bekliyor.', step: 'supplier' as const },
    { tone: 'info' as const, text: 'Rapor yüklenmesi gerekiyor.', step: 'report_writing' as const },
    { tone: 'info' as const, text: 'Finans onayı bekliyor.', step: 'sent_for_approval' as const },
  ],
  inspectors: [
    {
      id: 'i1',
      name: 'Mehmet Kaya',
      region: 'Kadıköy',
      available: true,
      score: 4.8,
      lastWork: '16.07.2026',
      completedJobs: 42,
      phone: '0532 111 22 33',
      source: 'meridyen' as const,
    },
    {
      id: 'i2',
      name: 'Ayşe Demir',
      region: 'Üsküdar',
      available: true,
      score: 4.6,
      lastWork: '14.07.2026',
      completedJobs: 31,
      phone: '0533 222 33 44',
      source: 'meridyen' as const,
    },
    {
      id: 'i3',
      name: 'Can Yıldız',
      region: 'Ataşehir',
      available: false,
      score: 4.5,
      lastWork: '12.07.2026',
      completedJobs: 28,
      phone: '0534 333 44 55',
      source: 'vendor' as const,
    },
  ],
  suppliers: [
    {
      id: 's1',
      name: 'Abc Boya',
      serviceGroup: 'Boyacı',
      place: 'Kadıköy',
      rating: '4.8 (23)',
      avail: 'Müsait' as const,
    },
    {
      id: 's2',
      name: 'Renkli Boya',
      serviceGroup: 'Boyacı',
      place: 'Üsküdar',
      rating: '4.6 (18)',
      avail: 'Müsait' as const,
    },
    {
      id: 's3',
      name: 'Def Boya',
      serviceGroup: 'Boyacı',
      place: 'Ataşehir',
      rating: '4.4 (12)',
      avail: 'Sınırlı Müsait' as const,
    },
  ],
  googleAlternatives: [
    { name: 'Moda Boya Ustası', place: 'Kadıköy', rating: '4.3' },
    { name: 'Sahil Boya Servisi', place: 'Kadıköy', rating: '4.1' },
  ],
  waTemplates: [
    { type: 'randevu_sigortali', name: 'Sigortalı Randevu Bilgilendirme' },
    { type: 'randevu_tespitci', name: 'Tespitçi Görev Bilgilendirme' },
    { type: 'randevu_tedarikci', name: 'Tedarikçi Görev Bilgilendirme' },
    { type: 'dijital_onay', name: 'Dijital Onay Bildirimi' },
  ],
  waHistory: [
    {
      when: '18.07.2026 14:22',
      by: 'Ayşe Operatör',
      recipient: 'Ahmet Yılmaz',
      template: 'Sigortalı Randevu Bilgilendirme',
      status: 'Gönderildi',
    },
  ],
  report: {
    number: 'HR-2026-0042',
    revision: 0,
    status: 'Yazım Aşamasında',
    owner: 'Mehmet Kaya',
    updatedAt: '19.07.2026 15:40',
    total: '48.500 ₺',
    supplierCost: '32.000 ₺',
    actualExpense: '8.200 ₺',
    expectedIncome: '48.500 ₺',
    profit: '8.300 ₺',
    margin: '%17,1',
    vatNote: 'Kdv Hariç',
    missingDocs: 2,
    photoCount: 4,
    readyChecks: {
      reportComplete: false,
      docsComplete: false,
      photosComplete: true,
      financeReady: true,
      revisionOk: true,
    },
  },
  revisions: [
    {
      n: 0,
      date: '19.07.2026',
      by: 'Meridyen',
      reason: 'İlk rapor',
      note: 'İlk yazım başlatıldı.',
      active: true,
    },
  ],
};
