/**
 * MASTER referans önizleme verisi — ekran görüntüsü birebir görsel kabul için.
 * Kaynak: Ekran_Resmi_2026-07-20_22.15.21 (Yönetim Dashboard MASTER v3).
 * Üretim API’leri bağlandığında bu katman kaldırılır / gerçek veriye geçer.
 */

import type { DeptSlice, MarginPoint, TrendPoint } from './MgmtChartsRow';
import type { DeptFinanceRow } from './MgmtDepartmentTable';
import type { MgmtSummaryCell } from './MgmtExecutiveSummary';
import type { MgmtKpiItem } from './MgmtKpiRow';
import type { StaffProductivityRow } from './MgmtStaffTable';
import {
  FileCheck2,
  FolderOpen,
  Percent,
  Receipt,
  TrendingUp,
  Wallet,
} from 'lucide-react';

export const REFERENCE_KPIS: MgmtKpiItem[] = [
  {
    id: 'ciro',
    title: 'Toplam Ciro',
    value: '₺ 5.750.000',
    trendLabel: '+%18,6',
    trendTitle: '%18,6 önceki döneme göre',
    trendDirection: 'up',
    icon: TrendingUp,
    iconClass: 'bg-blue-50 text-[#2563EB]',
  },
  {
    id: 'gider',
    title: 'Toplam Gider',
    value: '₺ 4.250.000',
    trendLabel: '+%12,3',
    trendTitle: '%12,3 önceki döneme göre',
    trendDirection: 'up',
    icon: Receipt,
    iconClass: 'bg-emerald-50 text-[#16A34A]',
  },
  {
    id: 'kar',
    title: 'Toplam Kâr',
    value: '₺ 1.500.000',
    trendLabel: '+%32,4',
    trendTitle: '%32,4 önceki döneme göre',
    trendDirection: 'up',
    icon: Wallet,
    iconClass: 'bg-violet-50 text-[#7C3AED]',
  },
  {
    id: 'marj',
    title: 'Kâr Marjı',
    value: '%26,09',
    trendLabel: '+%8,4',
    trendTitle: '%8,4 önceki döneme göre',
    trendDirection: 'up',
    icon: Percent,
    iconClass: 'bg-amber-50 text-[#F59E0B]',
  },
  {
    id: 'acik',
    title: 'Açık Dosya',
    value: '342',
    trendLabel: '-%5,2',
    trendTitle: '%5,2 önceki döneme göre',
    trendDirection: 'down',
    icon: FolderOpen,
    iconClass: 'bg-cyan-50 text-cyan-700',
  },
  {
    id: 'tamamlanan',
    title: 'Tamamlanan Dosya',
    value: '1.245',
    trendLabel: '+%15,7',
    trendTitle: '%15,7 önceki döneme göre',
    trendDirection: 'up',
    icon: FileCheck2,
    iconClass: 'bg-slate-100 text-slate-700',
  },
];

export const REFERENCE_SUMMARY: MgmtSummaryCell[] = [
  {
    id: 'week',
    title: 'Son 7 Gün',
    primary: '8 Olumsuz Geri Bildirim Alındı',
    tone: 'alert',
    detailHref: '/panel/anketler/sonuclar',
  },
  {
    id: 'ciro',
    title: 'En Yüksek Ciro',
    primary: 'Hasar',
    secondary: '₺ 3.250.000 (%56,5)',
    tone: 'neutral',
    detailHref: '/panel/finans/karlilik',
  },
  {
    id: 'gider',
    title: 'En Yüksek Gider',
    primary: 'Tedarik Zinciri',
    secondary: '₺ 1.350.000 (%31,8)',
    tone: 'neutral',
    detailHref: '/panel/finans/masraflar',
  },
  {
    id: 'marj',
    title: 'En Yüksek Kâr Marjı',
    primary: 'Acil Yardım',
    secondary: '%34,2',
    tone: 'positive',
    detailHref: '/panel/finans/karlilik',
  },
  {
    id: 'dikkat',
    title: 'Dikkat Gereken',
    primary: 'Tedarik Zinciri Kâr Marjı Düşüyor',
    secondary: '↓ %-9,3',
    tone: 'warning',
    detailHref: '/panel/tedarikciler',
  },
  {
    id: 'personel',
    title: 'Öne Çıkan Personel',
    primary: 'Mehmet Kaya',
    secondary: 'Kâr Marjı %38,6',
    tone: 'positive',
    showAvatar: true,
    detailHref: '/panel/sahiplik',
  },
];

export const REFERENCE_TREND: TrendPoint[] = [
  { label: '01', revenue: 180, cost: 140, profit: 40 },
  { label: '05', revenue: 210, cost: 155, profit: 55 },
  { label: '10', revenue: 195, cost: 160, profit: 35 },
  { label: '15', revenue: 240, cost: 170, profit: 70 },
  { label: '20', revenue: 260, cost: 185, profit: 75 },
  { label: '25', revenue: 230, cost: 175, profit: 55 },
  { label: '30', revenue: 280, cost: 190, profit: 90 },
];

/** Toplam ₺5.750.000 — referans yüzdeler */
export const REFERENCE_DEPARTMENTS: DeptSlice[] = [
  { name: 'Hasar', value: 3250000, fill: '#2563EB' },
  { name: 'Acil Yardım', value: 1150000, fill: '#16A34A' },
  { name: 'Anket', value: 575000, fill: '#8B5CF6' },
  { name: 'Eksper', value: 460000, fill: '#F59E0B' },
  { name: 'Operasyon', value: 201250, fill: '#0EA5E9' },
  { name: 'Diğer', value: 113750, fill: '#94A3B8' },
];

export const REFERENCE_MARGINS: MarginPoint[] = [
  { label: '01', margin: 22 },
  { label: '05', margin: 24 },
  { label: '10', margin: 21 },
  { label: '15', margin: 26 },
  { label: '20', margin: 28 },
  { label: '25', margin: 25 },
  { label: '30', margin: 26 },
];

export const REFERENCE_DEPT_ROWS: DeptFinanceRow[] = [
  {
    department: 'Hasar',
    dailyRevenue: '₺ 125.000',
    weeklyRevenue: '₺ 780.000',
    monthlyRevenue: '₺ 3.250.000',
    dailyExpense: '₺ 88.000',
    weeklyExpense: '₺ 540.000',
    monthlyExpense: '₺ 2.180.000',
    dailyProfit: '₺ 37.000',
    weeklyProfit: '₺ 240.000',
    monthlyProfit: '₺ 1.070.000',
    dailyMargin: '%29,6',
    weeklyMargin: '%30,8',
    monthlyMargin: '%32,9',
    trend: '▲',
    openFiles: '186',
    closedFiles: '642',
  },
  {
    department: 'Acil Yardım',
    dailyRevenue: '₺ 42.000',
    weeklyRevenue: '₺ 265.000',
    monthlyRevenue: '₺ 1.150.000',
    dailyExpense: '₺ 27.000',
    weeklyExpense: '₺ 168.000',
    monthlyExpense: '₺ 756.000',
    dailyProfit: '₺ 15.000',
    weeklyProfit: '₺ 97.000',
    monthlyProfit: '₺ 394.000',
    dailyMargin: '%35,7',
    weeklyMargin: '%36,6',
    monthlyMargin: '%34,3',
    trend: '▲',
    openFiles: '74',
    closedFiles: '318',
  },
  {
    department: 'Anket',
    dailyRevenue: '₺ 18.000',
    weeklyRevenue: '₺ 112.000',
    monthlyRevenue: '₺ 575.000',
    dailyExpense: '₺ 11.000',
    weeklyExpense: '₺ 72.000',
    monthlyExpense: '₺ 360.000',
    dailyProfit: '₺ 7.000',
    weeklyProfit: '₺ 40.000',
    monthlyProfit: '₺ 215.000',
    dailyMargin: '%38,9',
    weeklyMargin: '%35,7',
    monthlyMargin: '%37,4',
    trend: '▲',
    openFiles: '28',
    closedFiles: '156',
  },
  {
    department: 'Eksper',
    dailyRevenue: '₺ 16.000',
    weeklyRevenue: '₺ 98.000',
    monthlyRevenue: '₺ 460.000',
    dailyExpense: '₺ 12.000',
    weeklyExpense: '₺ 74.000',
    monthlyExpense: '₺ 310.000',
    dailyProfit: '₺ 4.000',
    weeklyProfit: '₺ 24.000',
    monthlyProfit: '₺ 150.000',
    dailyMargin: '%25,0',
    weeklyMargin: '%24,5',
    monthlyMargin: '%32,6',
    trend: '▲',
    openFiles: '13',
    closedFiles: '40',
  },
  {
    department: 'Operasyon',
    dailyRevenue: '₺ 7.000',
    weeklyRevenue: '₺ 48.000',
    monthlyRevenue: '₺ 201.250',
    dailyExpense: '₺ 5.200',
    weeklyExpense: '₺ 34.000',
    monthlyExpense: '₺ 142.000',
    dailyProfit: '₺ 1.800',
    weeklyProfit: '₺ 14.000',
    monthlyProfit: '₺ 59.250',
    dailyMargin: '%25,7',
    weeklyMargin: '%29,2',
    monthlyMargin: '%29,4',
    trend: '▲',
    openFiles: '9',
    closedFiles: '22',
  },
  {
    department: 'Tedarik Zinciri',
    dailyRevenue: '₺ 22.000',
    weeklyRevenue: '₺ 145.000',
    monthlyRevenue: '₺ 620.000',
    dailyExpense: '₺ 31.000',
    weeklyExpense: '₺ 198.000',
    monthlyExpense: '₺ 845.000',
    dailyProfit: '₺ -9.000',
    weeklyProfit: '₺ -53.000',
    monthlyProfit: '₺ -225.000',
    dailyMargin: '-%40,9',
    weeklyMargin: '-%36,6',
    monthlyMargin: '-%36,3',
    trend: '▼',
    openFiles: '41',
    closedFiles: '89',
  },
];

export const REFERENCE_STAFF: StaffProductivityRow[] = [
  {
    id: '1',
    name: 'Mehmet Kaya',
    department: 'Hasar',
    taskDistribution: '48 görev',
    completedFiles: '42',
    successRate: '%94',
    avgResolution: '1,8 gün',
    profitContribution: '₺ 186.000',
    satisfaction: 4.8,
  },
  {
    id: '2',
    name: 'Ayşe Demir',
    department: 'Acil Yardım',
    taskDistribution: '36 görev',
    completedFiles: '33',
    successRate: '%91',
    avgResolution: '0,9 gün',
    profitContribution: '₺ 142.000',
    satisfaction: 4.6,
  },
  {
    id: '3',
    name: 'Can Öztürk',
    department: 'Anket',
    taskDistribution: '29 görev',
    completedFiles: '27',
    successRate: '%88',
    avgResolution: '2,1 gün',
    profitContribution: '₺ 98.000',
    satisfaction: 4.2,
  },
  {
    id: '4',
    name: 'Elif Yılmaz',
    department: 'Hasar',
    taskDistribution: '31 görev',
    completedFiles: '25',
    successRate: '%81',
    avgResolution: '2,4 gün',
    profitContribution: '₺ 76.000',
    satisfaction: 3.7,
  },
  {
    id: '5',
    name: 'Burak Şahin',
    department: 'Eksper',
    taskDistribution: '22 görev',
    completedFiles: '20',
    successRate: '%90',
    avgResolution: '1,5 gün',
    profitContribution: '₺ 64.000',
    satisfaction: 4.4,
  },
];

export const REFERENCE_SLA_PCT = 92;

/** SLA daire dilimleri — Zamanında / Geciken (toplam 100) */
export const REFERENCE_SLA_SLICES = [
  { name: 'Zamanında', value: 92, fill: '#16A34A' },
  { name: 'Geciken', value: 8, fill: '#EF4444' },
];

